### ISSUE TITLE
old patch not applied?

### ISSUE THREAD

**Issue by gariac** [kondrak/vkQuake2#109]
I am compiling the linux version.

I could not get around this error: 
ERROR: Couldn't load maps/ntro.inn.bsp
until I used this 8 year old patch:
[https://sourceforge.net/p/quake/patches/13/](url)
The patch file isn't suitable for the current rev of the software, but I read the patch file contents and patched the code by hand. 

Yeah I know this sounds crazy, but is it possible this patch was missed?

I'm now able to play the game and I have to say this looks incredible on modern hardware.

**Comment by kondrak** [comment]
Which distro are you using? I haven't seen this problem before, very odd.

**Comment by gariac** [comment]
#response_container_BBPPID{font-family: initial;font-size: initial;color: initial;}  I am using opensuse 15.2. There are numerous threads on the internet if you search for that error message.                                                                                                                                                                                                                                                                                                                         From: notifications@github.comSent: August 29, 2020 6:04 AMTo: vkQuake2@noreply.github.comReply-to: reply@reply.github.comCc: lists@lazygranch.com; author@noreply.github.comSubject: Re: [kondrak/vkQuake2] old patch not applied? (#109)  
Which distro are you using? I haven't seen this problem before, very odd.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kondrak** [comment]
I applied the patch now, please check the latest master branch and let me know if everything works fine.

**Comment by gariac** [comment]
#response_container_BBPPID{font-family: initial;font-size: initial;color: initial;}  Other than ++map versus map++, the patch is identical and should work. Since map isn't in an equation, the statements should work the same. Ok this works. What I did was save my game in progress by doing a cp - r baseq2 to a new directory. Initially the new build crashed, but I deleted the config.fig and the "save" directory and it works fine. Thanks. This Quake2 has all the original bugs like bodies halfway through walls, but that is the charm. One guy I killed fell on a case of shotgun shells and the two merged, just like it did back in the 90s. I wouldn't have it any other way. This is where I wget-ed  the pak files. Actually copied everything. https://q2.weba.ru/files/baseq2/The md5sum of the pak files matches the references I found.                                                                                                                                                                                                                                                                                                                         From: notifications@github.comSent: August 29, 2020 2:16 PMTo: vkQuake2@noreply.github.comReply-to: reply@reply.github.comCc: lists@lazygranch.com; author@noreply.github.comSubject: Re: [kondrak/vkQuake2] old patch not applied? (#109)  
I applied the patch now, please check the latest master branch and let me know if everything works fine.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kondrak** [comment]
Glad that it works and that you enjoy the original bugs the same way I do!
