### ISSUE TITLE
Not an Issue with vkq2 but....

### ISSUE THREAD

**Issue by gribbs88** [kondrak/vkQuake2#110]
HI, 

The 1.5.3 release is not showing up on the release page and the link to it in the email does not work.

Cheers,

**Comment by kondrak** [comment]
Hi!
The 1.5.3 release will be back shortly, I actually removed it soon after I published it because I realized there was "one more thing" I wanted to fix. Stay tuned!

**Comment by kondrak** [comment]
Aaaand done!
