### ISSUE TITLE
Can't switch to Vulkan render using SwiftShader as a render

### ISSUE THREAD

**Issue by opain-replika** [kondrak/vkQuake2#115]
Hello,
The game always defaults to software render, switching to opengl starts using my GPU which doesn't support Vulkan.
I use means of SwiftShader vulkan software render to run some apps/games that require vulkan or higher level of DirectX (using wined3d with vulkan backend).
Wanted to test performance of this software vulkan render in vkQuake 2 but can't switch to vulkan mode.
Either the problem is with switching gpus (which technically I have 3 (2 radeons and swiftshader)) or in some other thing.

P.S. vkQuake (1) runs on it perfectly fine (even if slow).

**Comment by kondrak** [comment]
Hi!

Working with emulation software is beyond the scope of this project, without logs I can only guess what's wrong here. I suggest you try Yamagi Quake 2 for performance comparision - the project is now using vkQuake2's Vulkan renderer and from what I've heard it works with SwiftShader just fine (albeit slow), so this is the best bet for you to get it running!

**Comment by opain-replika** [comment]
Yamagi Quake 2 doesn't work either.

**Comment by kondrak** [comment]
Strange, I remember a message there saying that it worked with SwitfShader, in that case I'm not sure what changed.
