### ISSUE TITLE
umm dont use r1 code

### ISSUE THREAD

**Issue by xboxownzuall** [kondrak/vkQuake2#119]
Please stop using r1 quake 2 code base it's complete garbage, use the games default 3.20 code base this is exactly why the rocket's lighting color isnt correct and the games machine gun muzzleflash is broken without v sync because it's broken in r1 and it remains broken in yamagi because you built this thing off sucky r1 quake 2 man lol JUST STOP!

vulkan quake 2 by kondrak is built off 3.20's code base and that's why the rockets lighting is rendered the correct color and the muzzleflash for the machine gun renderers properly even without v sync.

**Comment by xboxownzuall** [comment]
https://steamcommunity.com/app/2320/discussions/0/1471967615888972848/ 

Check this you can use any modern res even with quake 2 3.20 lol, guess what the machine guns muzzle flash renderers properly without v sync, how can you say you fixed a bunch of bugs when the damn lighting wont even render properly? More like r1 quake 2 broke stuff it didnt fix anything.

**Comment by xboxownzuall** [comment]
See this is the correct lighting for rocket tho.

https://imgur.com/a/Nbmm6zS

https://imgur.com/a/9RLRETV

**Comment by kondrak** [comment]
I think you posted that in the wrong project, so closing this.
