### ISSUE TITLE
windows: alt + tab  does not restore full desktop resolution

### ISSUE THREAD

**Issue by j4reporting** [kondrak/vkQuake2#125]
this is on win10  with  vkquake 1.5.6 win32 
Desktop resolution is 2560x1440
Game fullscreen resolution configured to 1920x1080

switching to desktop  via alt+tab,  left windows key, or CTRL + ESC   restores windows desktop in game resolution  1920x1080 and not 2560x1440

**Comment by kondrak** [comment]
Latest master branch now handles this, thanks for the report!
