### ISSUE TITLE
Windows ARM64 Support

### ISSUE THREAD

**Issue by ccallahan** [kondrak/vkQuake2#127]
Not an issue, as much as an inquiry. I have a ARM64 laptop running Windows 10 (Samsung Galaxy Book S). Would you have any interest in me compiling some ARM64 binaries? I have a friend who I can probably coax into testing it as well. If anyone can break it, it's a speedrunner.

**Comment by kondrak** [comment]
If you feel like tinkering with it, go ahead - I'm open to contributions. I don't own an ARM Windows machine, so I won't be able to do it myself. Having a Github Action (similar to other platforms right now) would be intersting too!
