### ISSUE TITLE
Music stops erroneously

### ISSUE THREAD

**Issue by RavenMacDaddy** [kondrak/vkQuake2#128]
I was on level 3 in the original when it happened, specifically when you open the door which you unlock with the key you get when you've activated a terminal, the door which is here:

![image](https://user-images.githubusercontent.com/67732686/114303703-c2ada600-9acf-11eb-97ba-b20f720caa1b.png)

The first level where you encounter the "trespasser" guys with a grenade launcher and a minigun.

It happens on level 2 of mission pack Zaero as well.

It seems to happen any time some sort of transition trigger is activated, like opening a locked door or approaching the exit of a level.

**Comment by RavenMacDaddy** [comment]
After more testing it seems like it's already the default, so maybe I just stumbled into some sort of bug that made it stop? I believe was on level 3 in the original when it happened. The first level where you encounter the "trespasser" guys with a grenade launcher and minigun.

**Comment by kondrak** [comment]
This is the original game's behavior. Might as well be an intended design choice by Quake 2 team to emphasize certain events - either way not something that needs actual fixing.
