### ISSUE TITLE
Xatrix won't start

### ISSUE THREAD

**Issue by NineKain** [kondrak/vkQuake2#130]
When I use the "game xatrix" command, it seems that it changes to it, but when I start a new game, base Quake 2 starts

**Comment by RavenMacDaddy** [comment]
Try +set game xatrix.
This is what works for my scoop manifest and follows the same command structure as vkQuake.

**Comment by NineKain** [comment]
You mean in the autoexec.cfg? I'll try later

**Comment by RavenMacDaddy** [comment]
Just tested with your method and that works too, so something's probably missing in terms of files.

I get the same behavior as yours if files are indeed missing.

**Comment by NineKain** [comment]
I copied the base2, xatrix and rogue folders from my official Steam installation, I dunno what I'm missing

**Comment by RavenMacDaddy** [comment]
You're right, I was testing with yquake2 and was convinced that the results would be the same, this indeed seems to be a bug.

You would need to create a shortcut in the meantime with the "+set game xatrix" argument (without quotation marks).

**Comment by NineKain** [comment]
Thanks!

**Comment by kondrak** [comment]
I take it you solved the problem, so closing this.
