### ISSUE TITLE
[Request] Support high framerates

### ISSUE THREAD

**Issue by RavenMacDaddy** [kondrak/vkQuake2#131]
Are there any plans to support higher framerates, in parity with other ports like yquake2?

Thank you for your work so far - this port has got a distinct look that I really appreciate.

**Comment by kondrak** [comment]
Hi!

If by "higher framerates" you mean removing the 1000 FPS cap then no, there are no plans to do it. The goal of this project is to be as faithful to the original as possible and removal of this cap would have a lot of implications: breaking physics to start with - it's simply too much effort compared to the actual gains.

**Comment by RavenMacDaddy** [comment]
Thing is the port is locked to the default lock of 83 FPS even if you go to the console and execute cl_maxfps _your preferred FPS cap_ and without accounting for it, simply raising the FPS cap will break the physics.

This is why I took yquake2 as the example since that sourceport has fixed the physics issues related to framerates past 83 FPS and therefore has no hard framerate cap.
