### ISSUE TITLE
Compile error on Ubuntu Focal (20.04)

### ISSUE THREAD

**Issue by Jaujon** [kondrak/vkQuake2#133]
When firing `make release` in the linux sub-directory, here's what I get as an error message:

```
../ref_vk/vk_common.c:1179:29: error: incompatible types when initializing type ‘enum VkStructureType’ using type ‘void *’
 1179 |  qvkshader_t shaders[2] = { VK_NULL_HANDLE, VK_NULL_HANDLE };
      |                             ^~~~~~~~~~~~~~
make[1]: *** [Makefile:1842: releasex64/ref_vk/vk_common.o] Error 1
make[1]: Leaving directory '/home/jaujon/vkQuake2/linux'
make: *** [Makefile:167: build_release] Error 2
```

All dependencies have been installed, latest Vulkan SDK installed with package manager.

**Comment by kondrak** [comment]
Thanks for the report, looks like definition of VK_NULL_HANDLE has changed - I'll look into it this week.

**Comment by Jaujon** [comment]
Thanks buddy you're the best.

**Comment by kondrak** [comment]
Check out the latest commit, should be fine now.
