### ISSUE TITLE
[macos] It seems all mods/mappacks lack custom weapons/features.

### ISSUE THREAD

**Issue by idchlife** [kondrak/vkQuake2#137]
Hello! I compiled everything for macos via command line. Then I copied all the default and mods directories from other installation of quake 2. Unfortunately, all modifications work just like Quake 2 map packs. No custom monsters, weapons and sometimes even elevators (they seem to have custom coding or something).

Maybe I need to compile something else for all the modifications?

**Comment by kondrak** [comment]
Not sure how to help you here, since I don't know which mod we're talking about. How do you start the game from cmd?

**Comment by idchlife** [comment]
@kondrak ./quake2 +set game rogue

I suspect that all modifications need additional compilations for macOS for some kind of .dll/.so files but I can't seem to learn how to do that... Am I looking in the right direction?

**Comment by kondrak** [comment]
Looks fine - are you sure you have relevant .pak files in the rogue directory? The .so files are built automatically with the rest of the game, so no need to add anything new here.

**Comment by idchlife** [comment]
@kondrak looks fine... There is no .so file though...

<img width="603" alt="image" src="https://user-images.githubusercontent.com/4563032/129877386-3054f61f-88a6-4d3b-8882-dd7708c501c6.png">


Maybe my workflow was wrong? First I built vkQuake2 via command line, then after I copied all needed files into the rogue/xatrix etc directories.

**Comment by idchlife** [comment]
NVM. I should've definetely first copy files for mods, then build. Everything is fine now! Thank you!
