### ISSUE TITLE
Slight Mechanical Destruction game DLL/SO for vkQuake2

### ISSUE THREAD

**Issue by a740g** [kondrak/vkQuake2#141]
This source port is amazing and is the only one that I use to play through the single player games and mods for Quake 2. However, this is missing support for Slight Mechanical Destruction (http://musashi.backshooters.com/smd.html).

Can you please check if support for SMD can be added? These may be helpful:
https://github.com/yquake2/slightmechanicaldestruction
http://musashi.backshooters.com/files/smd_kmq2.zip

**Comment by kondrak** [comment]
Hi there - I'll see what I can do - I might have some time to look into it during Christmas.

**Comment by kondrak** [comment]
The mod is not yet distributed as an official release, but feel free to checkout the latest master branch commit for working support or try out a pre-built test binary from GitHub Actions: https://github.com/kondrak/vkQuake2/actions/runs/1631565567  - let me know if you run into any issues while testing it!

**Comment by a740g** [comment]
Working like a charm so far with the test binaries. Thank you @kondrak
