### ISSUE TITLE
No way to uncap / change framrate cap

### ISSUE THREAD

**Issue by suLac4ever** [kondrak/vkQuake2#158]
I discovered your source port for QUake 2 today and I love it! Especially the option to disable texture filtering to get a nice pixelated look is beautiful. I also love the simplicity and portability of this port and everything works as expected (even mods and addons).

The only thing I couldn't figure out to to, was, how to uncap or change the framerate cap from the stock 83 fps.
I tried every one of the following known commands: https://www.pcgamingwiki.com/wiki/Quake_II#Frame_rate_.28FPS.29
... as well as "vk_maxfps" as a random guess.

Is this something, which just isn't implemented yet or is there a custom command for doing that in you port?
(If not, is there a chance you will implement such an option in the future?)

Thanks in advance! :)

**Comment by kondrak** [comment]
I'd given this some thought and decided to close the issue - the scope of change would be too big and beyond of what this project was all about from the start - if you need uncapped FPS, I'd suggest trying Yamagi Quake 2 or some other project that is still actively maintained. :)
