### ISSUE TITLE
CLI argument to disable music playback

### ISSUE THREAD

**Issue by Slider-Whistle** [kondrak/vkQuake2#159]
Hey, I realise this might be a bit of a silly request, but as awesome as the music sounds in idsoft games, sometimes I just like to play without it and appreciate the ambient grunts and screams of all the monsters. It would be great to have an option for this, without having to do something as cumbersome as set the music volume slider to zero, and then have to turn it back up once I do want to hear it again.
Doom has the "-nomusic" option and Quake has the slightly longer "-nocdaudio" parameter (+"-noextmusic" in quakespasm/vkquake).

Quake II reinvents things a bit by only including the vim-style +command system meaning the correct argument this time around would probably be "+cd off" or "+cd_nocd 1" (https://www.eecis.udel.edu/~portnoi/quake/quakeiicom.html) (don't know if this works with DOS executable or linux port as-is, haven't tried), but neither those or this port's "+miniaudio off" seem to have worked for me.

**Comment by kondrak** [comment]
Running the game with `+set no_music 1` will now turn off music by default from CLI.

**Comment by Slider-Whistle** [comment]
Hey, cool!
