### ISSUE TITLE
Appimage/Flatpak for Linux

### ISSUE THREAD

**Issue by CaptainMuskrat** [kondrak/vkQuake2#160]
I would like to request that the option of downloading an Appimage for Flatpak be made available for Linux users. As a Fedora user (more specifically Nobara Linux) it can be a pain to translate Ubuntu or Arch instructions for my distro, and I believe a one-size fits all option would be preferable.

**Comment by kondrak** [comment]
Unfortunately I can no longer do it and test it myself, since I don't have access to Linux - will leave this open for someone to grab.
