### ISSUE TITLE
[Issue] Gravity in the game does not allow us to find some secrets

### ISSUE THREAD

**Issue by Sergiut99** [kondrak/vkQuake2#163]
The first level of the game. Please take a look at the screenshot. The player must jump on the lower ledge (step). But the player can't do this because of the high gravity in the game. The player can't jump any higher. It is impossible to take this secret
Please make a fix for vkQuake.

p.s I can't use your sv_gravity variable for my autoexec. cfg. The engine doesn't see the value of this variable in my autoexec.cfg.

Sorry I wrote to this place. I just found the port developer page for quake 1
https://github.com/Novum/vkQuake/issues
But this developer has blocked the ability to pass issues for his port and I do not know what to do. I thought. that the VKQuake port is a universal program, but this is not the case yet...
![vkquake0000](https://github.com/kondrak/vkQuake2/assets/100404282/2ebd4985-feec-41b6-a5de-5f651457ce3d)

**Comment by kondrak** [comment]
Sorry, not much I can do about this, since both projects are completely independent of each other and unrelated.
