### ISSUE TITLE
Low FPS count

### ISSUE THREAD

**Issue by Fryziu** [kondrak/vkQuake2#169]
The difference between vkQuake2 and other OpenGL-based clients is an order of magnitude.
I Love the clarity and richness of colors and preserved original style, and I would like to play on FFA servers using this client, but the FPS count is a deal breaker.
Here is an example on YT
https://youtu.be/mNkRzev24Ig
Compiled and run on Linux Mint 
RTX 3060

**Comment by kondrak** [comment]
Hi! I assume this is OpenGL renderer in vkQuake2 - here there's not much that can be done without a major overhaul of the legacy renderer code, which is beyond the scope of this project. Back in the days, there were built-in limitations and caps in the original game code which also are present here when trying to use OpenGL - this is not present in Vulkan implementation.
