### ISSUE TITLE
VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR

### ISSUE THREAD

**Issue by Fryziu** [kondrak/vkQuake2#170]
../ref_vk/vk_common.c: In function ‘QVk_Init’:
../ref_vk/vk_common.c:1625:32: error: ‘VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR’ undeclared (first use in this function)
 1625 |                 createFlags |= VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR;
----
Vulkan Instance Version: 1.3.204
----
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
----
The newest version of vkQuake2

**Comment by kondrak** [comment]
Looks like you're trying to build with a Vulkan SDK which doesn't have that flag defined. Which version are you using?

**Comment by Fryziu** [comment]
1.3.275.0 downloaded from https://vulkan.lunarg.com/ gives me this error (I have to say it's a sizeable install ;-)
Version 1.3.224 installed on the older system compiles fine.
I have solved my problem with the low FPS.
It's my fault, I have used the debug version which murders efficiency, but now it's all fine https://youtu.be/gX-ueNU36Uo

**Comment by kondrak** [comment]
Good to hear you figured out your low FPS issues.
As for the compilation error - the only way for me to verify this was to bump SDK version on GH Actions (Ubuntu runner) and that seems to have passed through well. For the heck of it, can you try 1.3.268?

**Comment by kondrak** [comment]
Also - if you could attach your full build log it could potentially also help. One suspicion I have is that you might have by default installed some older Vulkan SDK in the system (via package manager or such) and it might be using that instead of the one you downloaded.

**Comment by kondrak** [comment]
I'm closing this for now, since build passes successfully (Ubuntu with latest Vulkan SDK) - feel free to reopen if you come up with additional info!
