### ISSUE TITLE
Could not load pics/colormap.pcx

### ISSUE THREAD

**Issue by dor666** [kondrak/vkQuake2#29]
Hi,

I had no issues compiling, but I get following messagebox when I try launch game:
![image](https://user-images.githubusercontent.com/1740971/50426628-49a0cb00-0893-11e9-8b8c-5cdcea531737.png)
I would like to play demo. Do I need to change anything in source/project?

**Comment by kondrak** [comment]
This error indicates missing game data files which are not included with the source code due to their size.
By default, the built executable ends up in Quake2 folder - make sure there's a baseq2 folder inside it with all necessary data paks - see the zip file on release page, it has everything you'll need.

**Comment by kondrak** [comment]
(I should probably update the README to be more specific about it. :) )

**Comment by dor666** [comment]
Thanks for quick replay. It works fine.
I misunderstood package with repository in README :) 
Then I started to search for "DEMO" defines in sources and tried to tweak it :).

**Comment by tojestzart** [comment]
Witam, mam paka0 oryginalnego z 97 roku w folderze baseq2, odpalając przez 2-wu klik wysypuje "Error during initialization".
testowane na vkquake2-1.4.0_win64.zip, win7x64

**Comment by idchlife** [comment]
@kondrak for some reason error persists...

![image](https://user-images.githubusercontent.com/4563032/128854209-76b730d8-583e-481c-bc43-128ed0db5c09.png)
 any idea how to overcome it?

**Comment by aculotarpa** [comment]
Same here
<img width="1180" alt="Schermata 2021-08-23 alle 15 27 27" src="https://user-images.githubusercontent.com/21076287/130455797-8dc52288-0145-41c7-9bbb-e53da225573f.png">

**Comment by mjr4077au** [comment]
Normally this happens when you extract an updated vkQuake2 over the top of your existing install and it replaces retail PAK files with demo ones. I sort of wish vkQuake2 didn't come with the demo content for this reason as I've been caught out before.

**Comment by idchlife** [comment]
@aculotarpa it helps starting quake2 from terminal instead of gui. It runs from there

**Comment by tojestzart** [comment]
@idchlife exe must be on top level, always, not in ctf folder, it doesnt see pak0.pak

**Comment by aculotarpa** [comment]
> @aculotarpa it helps starting quake2 from terminal instead of gui. It runs from there

Thank you @idchlife , it worked!
