### ISSUE TITLE
Please consider forking yamagi quake.

### ISSUE THREAD

**Issue by LethalManBoob** [kondrak/vkQuake2#33]
The lack of modern conveniences such as mouse wheel weapon select and persistent binds and a very frustrating console, i just dont see why anyone would use this. Beyond a tech demo, if anyone really should get enjoyment from this, yamagi forking is a must.

Regardless, i can say this is good work.

**Comment by kondrak** [comment]
Thanks for the comment! I'm quite aware that Yamagi is full of neat improvements over the original game. I have in fact added a few of those already but I wanted to stay as true as the original as possible.
With that said, the goal of this particular project is educational, so it was a deliberate choice to NOT use Yamagi as the base. I may submit a PR with Vulkan support at some point but I don't have such plans in the nearest future.
