### ISSUE TITLE
Windows desktop scaling

### ISSUE THREAD

**Issue by Flynt56** [kondrak/vkQuake2#38]
Looks like Windows desktop scaling messes with the game window. I'm playing on a QHD monitor with scaling set to 125% and noticed a problem when setting the game's resolution from the default (1920x1080) to my monitor's native resolution (2560x1440). I've only tried the Vulkan renderer...

The game window stretches down and right, out of the window bounds. This problem makes the game quite tough to play with the in-game screen size set to max, as you can't see a portion of the game window.

> Image 1 - Desktop: 2560x1440 (100% scaling) | Game: 2560x1440 (Vulkan) | Image has been brightened for clarity | Game screen size was set to lowest for comparison
![vkq2_qhd_100](https://user-images.githubusercontent.com/33006333/50574102-cecf3700-0de1-11e9-9b08-91ef9a1240a5.jpg)

> Image 2 - Desktop: 2560x1440 (**125% scaling**) | Game: 2560x1440 (Vulkan) | Image has been brightened for clarity | Game screen size was set to lowest for comparison
![vkq2_qhd_125](https://user-images.githubusercontent.com/33006333/50574104-d1ca2780-0de1-11e9-911c-038ded155f88.jpg)

Related specs:
- Windows 10 Home x64, 1809 (17763.195)
- Nvidia GeForce GTX 1060 (Driver version: 417.35)

**Comment by kondrak** [comment]
Thanks! I'll look into it.
