### ISSUE TITLE
(Linux VK) No fullscreen

### ISSUE THREAD

**Issue by ivohuisjes** [kondrak/vkQuake2#49]
I compiled the linux build under ubuntu 18.04.
I can't run the game in full screen. When I change to fullscreen and apply the settings, the game immediately returns to windows mode.

**Comment by kondrak** [comment]
Does this happen for every screen resolution you try? Sounds like the one you're trying is not supported by your GPU.

**Comment by kondrak** [comment]
Thanks, I'll have a look into this.

**Comment by kondrak** [comment]
Btw, which GPU drivers are you using?

**Comment by ivohuisjes** [comment]
415.25

**Comment by ivohuisjes** [comment]
When i try to change to fullscreen (1920x1080), I noticed in the console log this:

```
Initializing Vulkan display
...setting fullscreen mode 10: 2048 1536
...
...trying swapchain extent: 2048x1536
```
It looks like it is not detecting the correct resolution?

**Comment by kondrak** [comment]
Ok, that's definitely a bug, I'll check it out tonight

**Comment by kondrak** [comment]
Latest commit in master fixes the mismatched resolutions - can you check if you can get FullHD to work in fullscreen now? I'm using mesa drivers and an Intel GPU and so far cannot reproduce the issue.

**Comment by kondrak** [comment]
Good to hear, thanks for the report!
