### ISSUE TITLE
Gamepad analog stick setup

### ISSUE THREAD

**Issue by AlonzoTG** [kondrak/vkQuake2#51]
Need a way to set up modern gamepad laout with move, look and fire controls on Left stick, right stick, and trigger respectively. Can assign SOME binary buttons but not the analog controls, or just default to standard x-pad layout.

**Comment by kondrak** [comment]
Sorry but it's unlikely I will implement this - there are better source ports out there and the purpose of this project is purely to focus on Vulkan. Pull Requests are welcome, though! 🙂
