### ISSUE TITLE
Cannot select custom native resolution

### ISSUE THREAD

**Issue by smeep0** [kondrak/vkQuake2#58]
I cannot seem to select any other resolutions other than the ones listed in the site (1920x1080, 2560x1440, and 3840x2160). My current desktop/monitor resolution is only 1366x768@60Hz, but the option does not seem to be selectable. I tried making an autoconfig.cfg file in the baseq2 folder using "vk_customwidth" and "vk_customheight" parameters, but to no avail.

**Comment by kondrak** [comment]
I added the missing r_customwidth and r_customsupport and also made 1366x768 available in the video menu since it's quite popular on some laptops.

**Comment by livello** [comment]
@kondrak  what about 21:9?
3440x1440 for me

**Comment by kondrak** [comment]
You should be able to set it with r_customwidth and r_customheight commands. Be sure to also set video mode to "custom" in the Video menu afterwards. This is the same behavior as in case of Yamagi Quake 2.
