### ISSUE TITLE
Crashing in linux fedora 29

### ISSUE THREAD

**Issue by Rugaliz** [kondrak/vkQuake2#62]
I get this crash after compiling version 1.0.0 , previous version worked fine.

------------------------------------
------- Loading ref_vk.so -------
LoadLibrary("/mnt/cbadcb4e-7a47-4961-8979-89c4012e91dd/Lutris Virtual Drives/GOG/drive_c/GOG Games/Quake II/ref_vk.so")
ref_vk version: Vulkan (vkQuake2 v1.0.0)
Initializing Vulkan display
...setting fullscreen mode 10: 1600 1200
Using XFree86-VidModeExtension Version 2.2
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0x17
  Serial number of failed request:  17
  Current serial number in output stream:  24

**Comment by kondrak** [comment]
Can you delete your config.cfg and try again?

**Comment by Rugaliz** [comment]
That fixed it! Thanks, it was a very simple solution. hmm maybe i'll have to do this every version upgrade.

**Comment by kondrak** [comment]
Glad it helped!
