### ISSUE TITLE
Support for 'The Reckoning' and 'Ground Zero' (xatrix and rogue)

### ISSUE THREAD

**Issue by tux-fan** [kondrak/vkQuake2#64]
Dear kondrak,
I've added the sources for xatrix (The Reckoning) and rogue (Ground Zero) mission-packs to my local copy of your vkQuake2 port and checked both mission-packs with linux Ubuntu 18.04, Vulkan 1.1.101 and nVidia 418.56 without problems.

If you're interested in I can add these sources to your project. Before I do so I have to learn how to submit the software into your git repository :)

This said, please comment this issue or drop me an eMail to 'webmaster@tux-fan.de' (I more often check my mail than I check other message sources)

best regards (and thanks for your work)
Guido Wüppenhorst a.k.a tux-fan

**Comment by kondrak** [comment]
Thanks for confirming that mission packs actually work! I suspected there should be no problems with them.
Not sure what the source code for those looks like but we can start with you making it available on Github somewhere, so I can have a look. I suspect some work might be needed to make it work on Windows and MacOS.
