### ISSUE TITLE
Map version differs from server

### ISSUE THREAD

**Issue by gribbs88** [kondrak/vkQuake2#67]
Hello, 
I'm getting this error when I connect to a server, custom or q2dm maps, and multiple servers. I'm runnig Slackware 14.2.

**Comment by gribbs88** [comment]
Ok, it works fine on windows for connecting to servers but on Kubuntu and Slackware - no dice. Even if I DL the map from the server it says the same thing on Linux.

**Comment by kondrak** [comment]
What's the full error message? It should be in the form of "Local map version differs from server: %i != '%s'"

**Comment by gribbs88** [comment]
Hello, here is the error;

 Local map version differs from server: -717660672 != '-1301042123'

**Comment by gribbs88** [comment]
here's the entire console :

bash-4.3$ cd /home/choops/Downloads/vkQuake2-master/linux/releasex64-glibc
bash-4.3$ ./quake2 +connect 23.227.170.222:27913
Added packfile ./baseq2/pak0.pak (3386 files)
Added packfile ./baseq2/pak1.pak (279 files)
Added packfile ./baseq2/pak2.pak (2 files)
execing default.cfg
execing config.cfg
Console initialized.

------- sound initialization -------
Setting up ALSA driver .....
Low Performance 11KHz.
sound sampling rate: 11025
------------------------------------
------- Loading ref_vk.so -------
LoadLibrary("/home/choops/Downloads/vkQuake2-master/linux/releasex64-glibc/ref_vk.so")
ref_vk version: Vulkan (vkQuake2 v1.1.1)
Initializing Vulkan display
...setting fullscreen mode 3: 640 480
Using XFree86-VidModeExtension Version 2.2
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
...created Vulkan instance
...created Vulkan surface
...found 1 Vulkan-capable device(s)
...created Vulkan memory allocator
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
...present mode VK_PRESENT_MODE_MAILBOX_KHR not supported, using present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
...trying swapchain extent: 640x480
...trying swapchain image format: 44
...created Vulkan swapchain
...created synchronization objects
...created Vulkan renderpass
...created Vulkan MSAAx4 renderpass
...created Vulkan command pools
...created depth buffer
...created MSAAx4 depth buffer
...created MSAAx4 color buffer
...created 2 Vulkan image view(s)
...created 2 Vulkan framebuffers
...created 2 Vulkan MSAA framebuffers
...created 2 Vulkan commandbuffers
Successfully initialized Vulkan!

öëÑõáëå² ö±®±®±
------------------------------------
Vulkan API: 1.1
Header version: 70
Devices found:
   #0: GeForce GTX 660
Using device #0:
   deviceName: GeForce GTX 660
   driverVersion: 430.14.0 (0x6B838000)
   apiVersion: 1.1.99
   deviceID: 4544
   vendorID: 0x10DE (NVIDIA)
   deviceType: VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
   gfx/present/transfer: 0/0/1
Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
Swapchain image format: 44
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
Enabled layers: 
------------------------------------
CDAudio_Init: open of "/dev/cdrom" failed (123)
====== Quake2 Initialized ======

Connecting to 23.227.170.222:27913...
23.227.170.222:27913: challenge
23.227.170.222:27913: client_connect




Outer Courts

------- sound initialization -------
Setting up ALSA driver .....
Low Performance 11KHz.
sound sampling rate: 11025
------------------------------------
Shutting down Vulkan
------- Loading ref_vk.so -------
LoadLibrary("/home/choops/Downloads/vkQuake2-master/linux/releasex64-glibc/ref_vk.so")
Cmd_AddCommand: +mlook already defined
Cmd_AddCommand: -mlook already defined
Cmd_AddCommand: force_centerview already defined
ref_vk version: Vulkan (vkQuake2 v1.1.1)
Initializing Vulkan display
...setting fullscreen mode 3: 640 480
Using XFree86-VidModeExtension Version 2.2
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
...created Vulkan instance
...created Vulkan surface
...found 1 Vulkan-capable device(s)
...created Vulkan memory allocator
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
...present mode VK_PRESENT_MODE_MAILBOX_KHR not supported, using present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
...trying swapchain extent: 640x480
...trying swapchain image format: 44
...created Vulkan swapchain
...created synchronization objects
...created Vulkan renderpass
...created Vulkan MSAAx4 renderpass
...created Vulkan command pools
...created depth buffer
...created MSAAx4 depth buffer
...created MSAAx4 color buffer
...created 2 Vulkan image view(s)
...created 2 Vulkan framebuffers
...created 2 Vulkan MSAA framebuffers
...created 2 Vulkan commandbuffers
Successfully initialized Vulkan!

öëÑõáëå² ö±®±®±
------------------------------------
Vulkan API: 1.1
Header version: 70
Devices found:
   #0: GeForce GTX 660
Using device #0:
   deviceName: GeForce GTX 660
   driverVersion: 430.14.0 (0x6B838000)
   apiVersion: 1.1.99
   deviceID: 4544
   vendorID: 0x10DE (NVIDIA)
   deviceType: VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
   gfx/present/transfer: 0/0/1
Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
Swapchain image format: 44
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
Enabled layers: 
------------------------------------
********************
ERROR: Local map version differs from server: -332034350 != '-220880526'

********************
]quit
Couldn't write config.cfg.
Shutting down Vulkan
recursive shutdown
bash-4.3$

**Comment by kondrak** [comment]
I can't think of a reason why this would happen - the network code remained unchanged from the original, so it's unlikely that the logic/checksum calculation function is broken. Is the working Windows version also 64 bit? Does it work with 32 bit binary just as well?

**Comment by gribbs88** [comment]
I have not tried the 32 bit binaries, windows was 64 bit as well.

**Comment by kondrak** [comment]
Can you give me some steps to reproduce (even with how you start the server etc.)? I'll see if I can get it on my Linux laptop.

**Comment by gribbs88** [comment]
-It's pretty much how the console i pasted shows. I just cd into the folder where the release is built and run ./quake2 from there and connect to an ip address like +connect 23.227.170.222:27916, or even through a server browser.
-I tried separate folder in home diectory as well and even another distro -Kubuntu- with a newer vulkan sdk. 
-Tried downloading a map from the server but same issue even when the map came from the server. Weird! Oh well, no big deal if you can't hammer it out, sorry I'm not more help, my knowledge is basically how to compile and then run.

To make it, I cd into the linux subfolder and type "make release", if that helps.

**Comment by kondrak** [comment]
If it's consistent behavior then I should repro it easily. From what I understand this happens with every server? I'll see what I can come up with.

**Comment by gribbs88** [comment]
Yep, every server out the 6 or so i tried, some running q2admin, others not. Even one i ran from a q2pro install on the same machine. Thanks for looking at this issue.

**Comment by kondrak** [comment]
Latest master branch should now work as expected, thanks for catching this!

**Comment by gribbs88** [comment]
Thanks for the fix. Works great!

Cheers,
