### ISSUE TITLE
Lighting is chunky?

### ISSUE THREAD

**Issue by mjr4077au** [kondrak/vkQuake2#70]
Is the lighting meant to be so chunky?

![image](https://user-images.githubusercontent.com/48643140/60509882-59510e80-9d11-11e9-9579-05d0a6d96e4d.png)

Lighting from explosions at the start of game and from your blaster are also equally chunky.

**Comment by kondrak** [comment]
Check the video menu and see what option you have set for texture filtering - looks like hete it's switched to nearest instead of default linear.

**Comment by mjr4077au** [comment]
That's right, I am using nearest filtering as I prefer unfiltered textures, but I guess I prefer filtered lighting.

Is it much work splitting the filtering into separate options for lighting and textures? Most other engines where I would use GL_NEAREST_MIPMAP_LINEAR wouldn't affect the lighting like this.

**Comment by kondrak** [comment]
I guess I could do that, I'm away now but will look into it next eeek.

**Comment by mjr4077au** [comment]
Sounds awesome, thanks! 😃
