### ISSUE TITLE
VS2019 CE 16.2+Clang -> 2 errors

### ISSUE THREAD

**Issue by donizettilorenzo** [kondrak/vkQuake2#73]
2 errors building the x64 release version using Clang and the master tree (1.3.0 too)

-> https://postimg.cc/Kkx9pVwZ

Can you solve these issues, kondrak?

**Comment by kondrak** [comment]
Thanks for the report, I'll have a look at it tonight.

**Comment by kondrak** [comment]
Latest master branch should now work fine.
