### ISSUE TITLE
added unofficial zaero mod

### ISSUE THREAD

**Issue by tux-fan** [kondrak/vkQuake2#80]
Dear Krzysztof,

as you might remember I asked you (a while ago) to add xatrix and rogue mods to vkQuake2. As we all can see you have done it already.

Thanks alot for that :)

There is another mod for Q2 that is really fun to play. This mod is called 'Zaero'. Based on your awesome work I have integrated that mod into my local copy of vkQuake2. The result of that can be found here:  https://github.com/tux-fan/vkQ2withZaero
It compiles without errors/warnings with VS2017-Community and it ran without errors. (not testet on Linux or MacOS)

If you decide to integrate the zaero-things into your vkQuake2 I will switch my repo back to 'private' . I think there is no need for 2 versions of 'vkQuake2' where 99.9% of the work is yours.

Best regards
Guido a.k.a. tux-fan

**Comment by mjr4077au** [comment]
Just wondering why you didn't fork his repository to do the work, so then you could submit a pull request? Very hard to see the changes between the two now.

**Comment by kondrak** [comment]
Please fork vkQuake2, submit your changes there and I'll review it + test it on Linux and MacOS as well.

**Comment by kondrak** [comment]
@tux-fan any comment on your side?

**Comment by tux-fan** [comment]
The fork, pull request thing:
I've made a 'fork' of your vkQuake2 and cloned your files. I've copied the Zaero things in that directory. When I try to add my files it says "too many files to add" ( or something like that)
I think I need further readings on how github works :)

**Comment by kondrak** [comment]
Did you make any significant changes outside the zaero directory? If not, I might pull it in myself.

**Comment by tux-fan** [comment]
modified files are:
linux/Makefile
README.md
quake2.sln

added Code::Blocks project file:
linux/quake2.cbp

**Comment by kondrak** [comment]
Quake II: Zaero expansion support has now landed on the master branch. Thanks for your interest!
