### ISSUE TITLE
3D Positional Audio (not EAX)

### ISSUE THREAD

**Issue by donizettilorenzo** [kondrak/vkQuake2#82]
I see vkQuake2 doesn't use OpenAL for audio (as other ID2 Tech variants do), but the classic DirectSound.
Problem is, it's not positional at all, it's only the original stereo implementation.

For the original Q2 3.20 there was a patch long time ago (1999): https://web.archive.org/web/19991004033555/http://www.earsound.com/titles/quake2.html

Can you do something similar for vkQuake2 (maintaining Direct Sound as API) ?
Can you make it compatible with IndirectSound? https://www.indirectsound.com/

**Comment by kondrak** [comment]
Hi!

I'm sorry but audio improvements like this are beyond the scope of this project which is focused on Vulkan graphics. The original patch doesn't seem to be open-sourced (and apparently it wasn't compatible with mission packs etc.), so it's difficult for me to estimate the actual effort here. I might have a look at this in the future but it's not likely to happen anytime soon.

For the time being, I strongly recommend trying Yamagi Quake 2 - it's a port focused on enhancing the entire game and as far as I know it has support for positional audio as well!

**Comment by donizettilorenzo** [comment]
Of course, but no other "modern day" Q2 still used DirectSound. It's why I asked !
