### ISSUE TITLE
PNG/JPEG Textures Pack support

### ISSUE THREAD

**Issue by donizettilorenzo** [kondrak/vkQuake2#83]
A request!
PNG/JPEG support for these:

https://github.com/Calinou/quake2-neural-upscale/releases (AI enhanced !)
http://quakeservers.nquake.com/nquake2-addon-textures.zip

and others

**Comment by kondrak** [comment]
Hi!

This is slightly beyond the scope of what I want to do with this project (focus on Vulkan development) - I suggest you try playing a different port that's capable of supporting custom texture paks like these.
