### ISSUE TITLE
Keybind changes in game also have their defaults 

### ISSUE THREAD

**Issue by AluminumHaste** [kondrak/vkQuake2#87]
Whenever I customize my controls in game, I exit and re-enter and they all have the changes I made AND their defaults.
I don't want those defaults set. If I unbind a key to nothing, it should remain nothing.

After clearing the keybinds and setting it up the way I want:
![quake2vk_custom](https://user-images.githubusercontent.com/4510040/76374644-33f1b700-631a-11ea-93c6-19daee62d9ea.gif)

After closing the game and re-opening it:
![quake2vk_custom02](https://user-images.githubusercontent.com/4510040/76374654-394f0180-631a-11ea-8db6-b4f7d38c47c2.gif)

**Comment by kondrak** [comment]
Hi!
This ia a designed feature of Quake 2 and one that involves processing a `default.cfg` file embedded in one of the game's pak files. CTRL and MOUSE1 (possibly some other keys as well) are special cases and if they're unbound, the scripts assigns their pre-assigned action. I suggest you create an `autoexec.cfg` file and add `unbind CTRL` to it if you really care about having it unbound at all times. Modifying the game code here seems like a wasted effort.
