### ISSUE TITLE
Lift VK_IMAGE_USAGE_TRANSFER_SRC_BIT requirement for the swapchain

### ISSUE THREAD

**Issue by kvark** [kondrak/vkQuake2#90]
Vulkan swapchains only guarantee support for COLOR_ATTACHMENT usage. If I understand correctly, vkQuake2 only uses `VK_IMAGE_USAGE_TRANSFER_SRC_BIT` for screenshots, so it's not essential to the task. Could we make the screenshot support optional instead of aborting when this usage is not exposed?

**Comment by kondrak** [comment]
I now made that usage flag optional, so screenshots are disabled if it's not present.
