### ISSUE TITLE
Fullscreen cause infinite reload (linux)

### ISSUE THREAD

**Issue by Elrondo46** [kondrak/vkQuake2#95]
Can you solve it ?

OS: Arch Linux
GPU: GTX 1070
Nvidia Drivers: 440.82

I've no problems with other vulkan games including Wine with DXVK

**Comment by kondrak** [comment]
Cannot reproduce. Which Vulkan SDK are you using? Also, please paste terminal output here with logs so that I can see potential error message.

**Comment by Elrondo46** [comment]
There is no error messages in Terminal, just infinite reload I use the last Gnome version.

**Comment by kondrak** [comment]
There has to be console output in the terminal, please check again. Can't help much without that information I'm afraid (I'm using Gnome as well).

**Comment by Elrondo46** [comment]
I want to help you but I can just make a video host on peertube instance if you want, there is no debug trace....

**Comment by kondrak** [comment]
When you run the game directly in Terminal., the Quake console prints its output there. Initialization process must be failing somewhere and this output can help. You could also try the debug build and see if it behaves differently. Does the game work in windowed mode?

**Comment by Elrondo46** [comment]
Oh watch this in debug at restart
QVk_EndFrame(): received VK_ERROR_OUT_OF_DATE_KHR after vkQueuePresentKHR - restarting video!

**Comment by Elrondo46** [comment]
There was the same problem in vkquake: https://github.com/Novum/vkQuake/issues/114

**Comment by kondrak** [comment]
Ok, so I understand that it keeps happening all the time?

**Comment by Elrondo46** [comment]
All the time I want fullscreen

**Comment by Elrondo46** [comment]
Window mode is not affected

**Comment by kondrak** [comment]
Full Terminal output would be still useful her., so please paste here everything you can see starting from application launch.

**Comment by Elrondo46** [comment]
Debug

`╰─ ./quake2
Added packfile ./baseq2/pak0.pak (3307 files)
execing default.cfg
execing config.cfg
Console initialized.

------- sound initialization -------
Setting up ALSA driver .....
High Quality 48KHz.
sound sampling rate: 48000
------------------------------------
------- Loading ref_vk.so -------
LoadLibrary("/opt/vkquake2/ref_vk.so")
ref_vk version: Vulkan (vkQuake2 v1.4.4)
Initializing Vulkan display
...setting mode 11: 1920 1080
Using XFree86-VidModeExtension Version 2.2
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
...created Vulkan instance
...created Vulkan surface
...found 1 Vulkan-capable device(s)
...created Vulkan memory allocator
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
...using present mode: VK_PRESENT_MODE_FIFO_KHR
...trying swapchain extent: 1920x1080
...trying swapchain image format: 44
...created Vulkan swapchain
...created synchronization objects
...created 3 Vulkan render passes
...created Vulkan command pools
...created world depth buffer
...created UI depth buffer
...created world color buffer
...created world postpocess color buffer
...created MSAAx4 color buffer
...created 2 Vulkan image view(s)
...created 2 Vulkan framebuffers
...created 2 Vulkan commandbuffers
Successfully initialized Vulkan!

������岠������
------------------------------------
Vulkan API: 1.2
Header version: 137
Devices found:
   #0: GeForce GTX 1070
Using device #0:
   deviceName: GeForce GTX 1070
   resolution: 1920x1080 (MSAAx4)
   driverVersion: 440.82.0 (0x6E148000)
   apiVersion: 1.1.119
   deviceID: 7041
   vendorID: 0x10DE (NVIDIA)
   deviceType: VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
   gfx/present/transfer: 0/0/1
Present mode: VK_PRESENT_MODE_FIFO_KHR
Swapchain image format: 44
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
Enabled layers: 
------------------------------------
CDAudio_Init: open of "/dev/cdrom" failed (2)
------- Loading gamex64.so -------
LoadLibrary (/opt/vkquake2/./baseq2/gamex64.so)
==== InitGame ====
------- Server Initialization -------
0 entities inhibited
0 teams with 0 entities
-------------------------------------
====== Quake2 Initialized ======

0.0.0.0:0: client_connect
------- Server Initialization -------
0 entities inhibited
0 teams with 0 entities
-------------------------------------

Changing map...
reconnecting...




Installation
Failed to open ./baseq2/music/track07.[ogg/flac/mp3/wav]: error -7
Shutting down Vulkan
------- Loading ref_vk.so -------
LoadLibrary("/opt/vkquake2/ref_vk.so")
Cmd_AddCommand: +mlook already defined
Cmd_AddCommand: -mlook already defined
Cmd_AddCommand: force_centerview already defined
ref_vk version: Vulkan (vkQuake2 v1.4.4)
Initializing Vulkan display
...setting fullscreen mode 11: 1920 1080
Using XFree86-VidModeExtension Version 2.2
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
...created Vulkan instance
...created Vulkan surface
...found 1 Vulkan-capable device(s)
...created Vulkan memory allocator
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
...using present mode: VK_PRESENT_MODE_FIFO_KHR
...trying swapchain extent: 1920x1080
...trying swapchain image format: 44
...created Vulkan swapchain
...created synchronization objects
...created 3 Vulkan render passes
...created Vulkan command pools
...created world depth buffer
...created UI depth buffer
...created world color buffer
...created world postpocess color buffer
...created MSAAx4 color buffer
...created 2 Vulkan image view(s)
...created 2 Vulkan framebuffers
...created 2 Vulkan commandbuffers
Successfully initialized Vulkan!

������岠������
------------------------------------
Vulkan API: 1.2
Header version: 137
Devices found:
   #0: GeForce GTX 1070
Using device #0:
   deviceName: GeForce GTX 1070
   resolution: 1920x1080 (MSAAx4)
   driverVersion: 440.82.0 (0x6E148000)
   apiVersion: 1.1.119
   deviceID: 7041
   vendorID: 0x10DE (NVIDIA)
   deviceType: VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
   gfx/present/transfer: 0/0/1
Present mode: VK_PRESENT_MODE_FIFO_KHR
Swapchain image format: 44
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
Enabled layers: 
------------------------------------
QVk_EndFrame(): received VK_ERROR_OUT_OF_DATE_KHR after vkQueuePresentKHR - restarting video!
Failed to open ./baseq2/music/track07.[ogg/flac/mp3/wav]: error -7
QVk_BeginFrame(): received VK_ERROR_OUT_OF_DATE_KHR after vkAcquireNextImageKHR - restarting video!
Shutting down Vulkan
------- Loading ref_vk.so -------
LoadLibrary("/opt/vkquake2/ref_vk.so")
Cmd_AddCommand: +mlook already defined
Cmd_AddCommand: -mlook already defined
Cmd_AddCommand: force_centerview already defined
ref_vk version: Vulkan (vkQuake2 v1.4.4)
Initializing Vulkan display
...setting mode 11: 1920 1080
Using XFree86-VidModeExtension Version 2.2
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
...created Vulkan instance
...created Vulkan surface
...found 1 Vulkan-capable device(s)
...created Vulkan memory allocator
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
...using present mode: VK_PRESENT_MODE_FIFO_KHR
...trying swapchain extent: 1920x1080
...trying swapchain image format: 44
...created Vulkan swapchain
...created synchronization objects
...created 3 Vulkan render passes
...created Vulkan command pools
...created world depth buffer
...created UI depth buffer
...created world color buffer
...created world postpocess color buffer
...created MSAAx4 color buffer
...created 2 Vulkan image view(s)
...created 2 Vulkan framebuffers
...created 2 Vulkan commandbuffers
Successfully initialized Vulkan!

������岠������
------------------------------------
Vulkan API: 1.2
Header version: 137
Devices found:
   #0: GeForce GTX 1070
Using device #0:
   deviceName: GeForce GTX 1070
   resolution: 1920x1080 (MSAAx4)
   driverVersion: 440.82.0 (0x6E148000)
   apiVersion: 1.1.119
   deviceID: 7041
   vendorID: 0x10DE (NVIDIA)
   deviceType: VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
   gfx/present/transfer: 0/0/1
Present mode: VK_PRESENT_MODE_FIFO_KHR
Swapchain image format: 44
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
Enabled layers: 
------------------------------------
Failed to open ./baseq2/music/track07.[ogg/flac/mp3/wav]: error -7
==== ShutdownGame ====
Shutting down Vulkan
recursive shutdown`

**Comment by kondrak** [comment]
Thanks, I'll see what I can find here.

**Comment by kondrak** [comment]
Does the game revert automatically once it fails entering fullscreen? That seems to be what I see here.

**Comment by Elrondo46** [comment]
Exact

**Comment by kondrak** [comment]
I haven't had a deeper look into it yet but for a quick test - can you open ref_vk/vk_rmain.c file in a text editor and comment out lines 1271 and 1272? They're responsible for reverting to windowed mode which in this particular case might not be necessary.

**Comment by Elrondo46** [comment]
Same errors
QVk_EndFrame(): received VK_ERROR_OUT_OF_DATE_KHR after vkQueuePresentKHR - restarting video!
QVk_BeginFrame(): received VK_ERROR_OUT_OF_DATE_KHR after vkAcquireNextImageKHR - restarting video!
Failed to open ./baseq2/music/track07.[ogg/flac/mp3/wav]: error -7
QVk_BeginFrame(): received VK_ERROR_OUT_OF_DATE_KHR after vkAcquireNextImageKHR - restarting video!

And infinite loop in fullscreen

**Comment by Elrondo46** [comment]
After searches, I've a doc can be interested but I'm not a C/C++ coder: https://github.com/KhronosGroup/Vulkan-Docs/issues/1126

**Comment by goodjaerb** [comment]
I just found this repo and I'm having this issue as well. I made a video to show what it looks like to me and attached the output. It is not reverting me to windowed mode. It just keeps restarting vulkan. If I set vid_fullscreen to 0 it runs fine in a window. I installed the latest LunarG Vulkan SDK and followed your directions. Might a different version work better?

https://www.youtube.com/watch?v=cjYPGA-6LQo

[vkQuake2_output.txt](https://github.com/kondrak/vkQuake2/files/4571610/vkQuake2_output.txt)

**Comment by kondrak** [comment]
I just pushed a slight behavior of what happens during a video restart on Vulkan. The problem here is that the error causes entire window to be rebuilt which now should not occur.
Please check the `odd` branch and let me know if the issue still presists :)

**Comment by kondrak** [comment]
@goodjaerb is this Gnome? Apparently there's an issue when toggling to fullscreen but what's happening here is pretty odd, there could be another bug.

**Comment by goodjaerb** [comment]
> @goodjaerb is this Gnome? Apparently there's an issue when toggling to fullscreen but what's happening here is pretty odd, there could be another bug.

It's Ubuntu 20.04, so yes I believe gnome. I will try the odd branch and let you know.

**Comment by goodjaerb** [comment]
@kondrak i compiled the ood branch and it appears to be working just fine!

**Comment by kondrak** [comment]
Great! @Elrondo46 does it work for you as well?

**Comment by Elrondo46** [comment]
Solved in odd branch :100: , I love playing it in fullscreen... Greetings from France in Lockdown actually :(

**Comment by kondrak** [comment]
Don't worry, the lockdown will end eventually, over here we're also stuck at home and slowly losing our minds because of it ;)
Thanks for the report and your help guys, I'll push a proper fix to master branch soon!

**Comment by Elrondo46** [comment]
Thanks
